name: ON_PUSH

on:
  push:
    branches:
      - develop
      - production

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      # Configure Git identity
      - name: Configure Git identity
        run: |
          git config user.email "iam.dikshant.dwivedi@gmail.com"
          git config user.name "dikshant dwivedi"

      # Semantic versioning
      - name: Bump Version and Create Release
        run: npm run release

      - name: Set path variable
        id: path
        run: |
          path=$(
            if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
              echo "dev.env"
            elif [[ "${GITHUB_REF}" == "refs/heads/production" ]]; then
              echo "prod.env"
            else
              echo "Unsupported branch"
              exit 1
            fi
          )

      - name: Set up environment
        uses: falti/dotenv-action@v1.0.4
        with:
          path: ${{ steps.path.outputs.path }}
          log-variables: true
          export-variables: true

      - name: Deploy to Staging
        run: |
          # Use the updated version in the deployment process
          VERSION=$(node -p "require('./package.json').version")
          echo "Deploying version $VERSION to Staging environment..."

          # Access the environment variable defined in the .env file during deployment
          echo "Deployment message: ${{ env.deploy_message }}"

      # Push changes back to the repository using the Personal Access Token
      - name: Push Changes
        run: git push --follow-tags "https://$GH_TOKEN@github.com/dikshantDwivediTechwondoe/CI-CD-sample.git"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
