name: ON_PUSH

on:
  push:
    branches:
      - develop
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "ENV_NAME=develop" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/production" ]; then
            echo "ENV_NAME=production" >> $GITHUB_ENV
          fi
          # Replace $DEPLOY_MESSAGE_ENV with your actual deploy message variable
          echo "DEPLOY_MESSAGE_ENV=${{ env.DEPLOY_MESSAGE_ENV }}" >> $GITHUB_ENV

      - name: Deploy to Staging
        env:
          ENV_NAME: ${{ env.ENV_NAME }}
          DEPLOY_MESSAGE_ENV: ${{ env.DEPLOY_MESSAGE_ENV }}
        run: |
          # Use the updated version in the deployment process
          VERSION=$(node -p "require('./package.json').version")
          echo "Deploying version $VERSION to $ENV_NAME environment..."

          # Access the environment variable defined in the .env file during deployment
          echo "Deployment message: $DEPLOY_MESSAGE_ENV"
